/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class StyleConstants {
  public static PERCENTAGE_100: string = '100%'
  public static PERCENTAGE_60: string = '60%'
  public static PERCENTAGE_0: string = '0%'
  public static SPACE_6: number = 6
  public static SPACE_24: number = 24
  public static NOTE_LIST_BACKGROUND: string = "#f1f3f5"
  public static DELETE_DEADLINE: number = 2592000000 // 30 days (30 * 24 * 60 * 60 * 1000)ms
  public static OPACITY_10: number = 0.1
  public static OPACITY_20: number = 0.2
  public static OPACITY_40: number = 0.4
  public static OPACITY_100: number = 1
}